export const dsTextareaSafelist = [
  'w-full',
  'rounded-md',
  'border',
  'bg-[var(--background)]',
  'px-3',
  'py-2',
  'text-[14px]',
  'text-[var(--foreground)]',
  'placeholder:text-[var(--muted-foreground)]',
  'transition-colors',
  'duration-150',
  'focus:outline-none',
  'focus-visible:ring-2',
  'focus-visible:ring-[var(--ring)]',
  'disabled:opacity-50',
  'disabled:cursor-not-allowed',
  'border-[var(--border)]',
  'border-[var(--ds-success)]',
  'focus-visible:ring-[var(--ds-success)]',
  'border-[var(--ds-warning)]',
  'focus-visible:ring-[var(--ds-warning)]',
  'border-[var(--ds-danger)]',
  'focus-visible:ring-[var(--ds-danger)]',
] as const