import { dsButtonSafelist } from '../DsButton/dsButtonStyles'

export const dsRadioSafelist = [...new Set([
  ...dsButtonSafelist,
  'opacity-50',
  'cursor-not-allowed',
  'cursor-pointer',
  'inline-flex',
  'items-center',
  'gap-2',
  'select-none',
  'focus-visible:outline-none',
  'focus-visible:rounded-[8px]',
  'focus-visible:shadow-[0_0_0_2px_var(--ring),0_0_0_4px_var(--background)]',
  'opacity-70',
  'h-4',
  'w-4',
  'rounded-full',
  'border',
  'flex',
  'justify-center',
  'transition-colors',
  'duration-150',
  'border-[var(--primary)]',
  'bg-[color-mix(in_srgb,var(--primary)_10%,var(--background))]',
  'border-[var(--border)]',
  'bg-[var(--background)]',
  'h-[6px]',
  'w-[6px]',
  'transition-[transform,opacity,background-color]',
  'bg-[var(--primary)]',
  'opacity-100',
  'scale-100',
  'bg-transparent',
  'opacity-0',
  'scale-75',
  'text-sm',
  'text-[var(--muted-foreground)]',
])] as const